name = "hugo-shortcode-gallery"
license = "MIT"
licenselink = "https://github.com/mfg92/hugo-shortcode-gallery/blob/master/LICENSE.md"
description = "A theme component with a gallery shortcode for the static site generator hugo."
homepage = "https://github.com/mfg92/hugo-shortcode-gallery"
demosite = "https://hitesh.one/hedwig-gallery/gallery"
tags = ["Gallery", "Responsive", "Shortcode"]
min_version = "0.121.2"

[author]
  name = "mfg92"
  homepage = "https://hitesh.one/hedwig-gallery"
